apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: example-crds
spec:
  annotations:
    approval.nephio.org/policy: initial
  upstream:
    package: IPAssignment
    repo: ipassignment
    revision: main
  downstream:
    package: example-ipassignment
    repo: mgmt
  pipeline:
    mutators:
    - image: gcr.io/kpt-fn/set-namespace:v0.4.1
      configMap:
        namespace: ipassignment-pv
